on:
  workflow_dispatch:
  schedule:
    # Runs every day At 01:00.
    - cron:  '0 1 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          target: 'https://sandbox-app.propine.com'
