on:
  workflow_dispatch:
  schedule:
    # Runs every Thu At 01:00.
    - cron:  '0 1 * * 4'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://sandbox-app.propine.com'
